recaptcha {
	// Set to false to disable the display of captcha
	enabled = false
	
	// These keys are generated by the ReCaptcha service
	publicKey = "6LdtSAMAAAAAAAuYKcqVpRv8qaTly8PVTKGLXCLS"
	privateKey = "6LdtSAMAAAAAAPFkwqh4XvMZe0WfWMoWbjneVA9-"
   
	// Include the noscript tags in the generated captcha
	includeNoScript = true
	
	// Communicate using HTTPS
	useSecureAPI = true
}