/*
 * Copyright 2002-2008 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
recaptcha {
	// Set to false to disable the display of captcha
	enabled = true
	
	// These keys are generated by the ReCaptcha service
	publicKey = "6Lf0fAMAAAAAADzyEjdMWKxydvi8oGaFh3k8frbN"
	privateKey = "6Lf0fAMAAAAAAORafZnM5VCJ9nCcD1nQ_hzsLBnX"
   
	// Include the noscript tags in the generated captcha
	includeNoScript = true
	
	// Communicate using HTTPS
	useSecureAPI = true
}